# Generated by Django 6.0 on 2025-12-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_waitlister'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='subexperience',
            field=models.TextField(blank=True, help_text='additional experience added as comma separated values', null=True),
        ),
    ]
