# Generated by Django 6.0 on 2025-12-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile_experience_profile_subexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
