# Generated by Django 6.0 on 2025-12-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subexperience',
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.TextField(blank=True, help_text='additional interests added as comma separated values', null=True),
        ),
    ]
