# Generated by Django 6.0 on 2025-12-24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_profile_subexperience_profile_interests'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuddyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('from_user', 'to_user')},
            },
        ),
        migrations.AddIndex(
            model_name='buddyrequest',
            index=models.Index(fields=['to_user', 'status'], name='api_buddyre_to_user_4a9a02_idx'),
        ),
        migrations.AddIndex(
            model_name='buddyrequest',
            index=models.Index(fields=['from_user', 'status'], name='api_buddyre_from_us_427f7f_idx'),
        ),
    ]
