# Generated by Django 6.0 on 2025-12-24 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_buddyrequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='buddyrequest',
            new_name='api_buddyre_to_user_964ce4_idx',
            old_name='api_buddyre_to_user_4a9a02_idx',
        ),
        migrations.RenameIndex(
            model_name='buddyrequest',
            new_name='api_buddyre_from_us_5698b4_idx',
            old_name='api_buddyre_from_us_427f7f_idx',
        ),
    ]
