# Generated by Django 6.0 on 2026-01-31 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_api_buddyre_to_user_4a9a02_idx_api_buddyre_to_user_964ce4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buddyrequest',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
