# Generated by Django 5.2.7 on 2026-02-28 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_message_attachment_message_attachment_mime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='partnership',
            field=models.ForeignKey(blank=True, help_text='If set, this goal is shared with the partnership.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='api.partnership'),
        ),
    ]
