# Generated by Django 6.0 on 2026-03-01 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_goal_partnership'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='goal',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
