# Generated by Django 6.0 on 2026-03-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_goal_category_goal_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='importance',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
