# Generated by Django 6.0 on 2026-04-25 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_task_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_date', models.DateField()),
                ('first_activity_at', models.DateTimeField()),
                ('last_activity_at', models.DateTimeField()),
                ('source', models.CharField(blank=True, default='', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'activity_date'], name='api_userdai_user_id_1191c1_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'activity_date'), name='uniq_user_activity_date')],
            },
        ),
    ]
