# Generated by Django 6.0 on 2026-04-25 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_userdailyactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InactivityNudgeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latest_activity_at', models.DateTimeField()),
                ('threshold_days', models.PositiveSmallIntegerField(default=14)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inactivity_nudge_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'threshold_days'], name='api_inactiv_user_id_f386b9_idx'), models.Index(fields=['latest_activity_at'], name='api_inactiv_latest__781efd_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'latest_activity_at', 'threshold_days'), name='uniq_inactivity_nudge_user_activity_threshold')],
            },
        ),
    ]
