# Generated by Django 6.0 on 2026-04-25 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_inactivitynudgelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='checkin_frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('3-DAYS', 'Every 3 Days'), ('WEEKLY', 'Weekly'), ('BI-WEEKLY', 'Bi-Weekly'), ('MONDAYS', 'Mondays'), ('TUESDAYS', 'Tuesdays'), ('WEDNESDAYS', 'Wednesdays'), ('THURSDAYS', 'Thursdays'), ('FRIDAYS', 'Fridays'), ('SARTUDAYS', 'Sartudays'), ('SUNDAYS', 'Sundays')], default='DAILY', max_length=20),
        ),
        migrations.CreateModel(
            name='CheckinReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reminder_for_date', models.DateField()),
                ('frequency', models.CharField(max_length=20)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_reminder_logs', to='api.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_reminder_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['reminder_for_date', 'frequency'], name='api_checkin_reminde_634b0a_idx')],
                'constraints': [models.UniqueConstraint(fields=('goal', 'user', 'reminder_for_date'), name='uniq_goal_user_checkin_reminder_for_date')],
            },
        ),
    ]
