# Generated by Django 6.0 on 2026-04-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_goal_checkin_frequency_checkinreminderlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='checkin_frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('3-DAYS', 'Every 3 Days'), ('WEEKLY', 'Weekly'), ('BI-WEEKLY', 'Bi-Weekly'), ('MONDAYS', 'Mondays'), ('TUESDAYS', 'Tuesdays'), ('WEDNESDAYS', 'Wednesdays'), ('THURSDAYS', 'Thursdays'), ('FRIDAYS', 'Fridays'), ('SATURDAYS', 'Saturdays'), ('SUNDAYS', 'Sundays')], default='DAILY', max_length=20),
        ),
    ]
