# Generated by Django 5.0.6 on 2026-05-08 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_goal_checkin_frequency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='goal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='api.goal'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goal',
            name='invite_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goal',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goal',
            name='shared_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_a_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_messages', to='api.message'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='partnership',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='api.partnership'),
        ),
        migrations.CreateModel(
            name='ConversationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_conversation_memberships', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_memberships', to='api.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='conversations', through='api.ConversationMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GoalMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_goal_memberships', to=settings.AUTH_USER_MODEL)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_memberships', to='api.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='goal',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='member_goals', through='api.GoalMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='conversationmembership',
            index=models.Index(fields=['conversation', 'user'], name='api_convers_convers_ec249e_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationmembership',
            constraint=models.UniqueConstraint(fields=('conversation', 'user'), name='uniq_conversation_member'),
        ),
        migrations.AddIndex(
            model_name='goalmembership',
            index=models.Index(fields=['goal', 'user'], name='api_goalmem_goal_id_970da3_idx'),
        ),
        migrations.AddConstraint(
            model_name='goalmembership',
            constraint=models.UniqueConstraint(fields=('goal', 'user'), name='uniq_goal_member'),
        ),
    ]
