# Generated by Django 6.0 on 2026-05-08

import uuid

from django.conf import settings
from django.db import migrations


def _invite_link(shared_id):
	base_url = (getattr(settings, 'PADLUPP_APP_URL', '') or 'https://app.padlupp.com').rstrip('/')
	return f'{base_url}/goals/?shared_id={shared_id}'


def forwards(apps, schema_editor):
	Goal = apps.get_model('api', 'Goal')
	GoalMembership = apps.get_model('api', 'GoalMembership')
	Partnership = apps.get_model('api', 'Partnership')
	Conversation = apps.get_model('api', 'Conversation')
	ConversationMembership = apps.get_model('api', 'ConversationMembership')

	for goal in Goal.objects.select_related('user', 'partnership', 'partnership__user_a', 'partnership__user_b').all():
		member_ids = []
		if goal.user_id:
			member_ids.append(goal.user_id)
		if goal.partnership_id:
			if goal.partnership.user_a_id:
				member_ids.append(goal.partnership.user_a_id)
			if goal.partnership.user_b_id:
				member_ids.append(goal.partnership.user_b_id)
		member_ids = list(dict.fromkeys([uid for uid in member_ids if uid]))

		for member_id in member_ids:
			GoalMembership.objects.get_or_create(goal_id=goal.id, user_id=member_id, defaults={'added_by_id': goal.user_id})

		if goal.is_public and not goal.shared_id:
			shared_id = uuid.uuid4()
			Goal.objects.filter(id=goal.id).update(shared_id=shared_id, invite_link=_invite_link(shared_id))
		elif goal.is_public and not goal.invite_link and goal.shared_id:
			Goal.objects.filter(id=goal.id).update(invite_link=_invite_link(goal.shared_id))

		if goal.partnership_id or len(member_ids) > 1:
			Goal.objects.filter(id=goal.id, is_shared=False).update(is_shared=True)
			conversation, _ = Conversation.objects.get_or_create(goal_id=goal.id, defaults={'is_group': True})
			if not conversation.is_group:
				Conversation.objects.filter(id=conversation.id).update(is_group=True)
			for member_id in member_ids:
				ConversationMembership.objects.get_or_create(
					conversation_id=conversation.id,
					user_id=member_id,
					defaults={'added_by_id': goal.user_id},
				)

	for partnership in Partnership.objects.select_related('user_a', 'user_b').all():
		conversation, _ = Conversation.objects.get_or_create(partnership_id=partnership.id, defaults={'is_group': False})
		if conversation.is_group:
			Conversation.objects.filter(id=conversation.id).update(is_group=False)
		ConversationMembership.objects.get_or_create(conversation_id=conversation.id, user_id=partnership.user_a_id)
		ConversationMembership.objects.get_or_create(conversation_id=conversation.id, user_id=partnership.user_b_id)


def backwards(apps, schema_editor):
	pass


class Migration(migrations.Migration):

	dependencies = [
		('api', '0022_conversation_goal_conversation_is_group_and_more'),
	]

	operations = [
		migrations.RunPython(forwards, backwards),
	]
