# Generated by Django 6.0 on 2026-05-08 16:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_conversation_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='conversations', through='api.ConversationMembership', through_fields=('conversation', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='goal',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='member_goals', through='api.GoalMembership', through_fields=('goal', 'user'), to=settings.AUTH_USER_MODEL),
        ),
    ]
