# Generated by Django 6.0 on 2026-06-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_conversation_members_alter_goal_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='tag',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
