# Generated by Django 6.0 on 2026-06-06 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_goal_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='tag',
        ),
    ]
