# Generated by Django 6.0.8 on 2026-09-14 10:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_goal_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmembership',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='kind',
            field=models.CharField(choices=[('user', 'User message'), ('goal', 'Goal event'), ('checkin', 'Check-in event')], default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='message',
            name='recalled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GoalCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_for', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('partial', 'Partially completed'), ('blocked', 'Blocked'), ('missed', 'Missed')], default='pending', max_length=20)),
                ('completion_percent', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('update_text', models.TextField(blank=True)),
                ('blocker', models.TextField(blank=True)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='checkin_evidence/')),
                ('evidence_view_once', models.BooleanField(default=False)),
                ('evidence_expires_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='api.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_checkins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoalCheckinBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_for', models.DateField()),
                ('badge_type', models.CharField(default='full_participation', max_length=40)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_badges', to='api.goal')),
            ],
        ),
        migrations.CreateModel(
            name='GoalCheckinEvidenceView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_views', to='api.goalcheckin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_evidence_views', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoalCheckinReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reaction', models.CharField(choices=[('support', 'Support'), ('celebrate', 'Celebrate')], max_length=20)),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='api.goalcheckin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_reactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubTaskReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reminder_for_date', models.DateField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='api.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtask_reminder_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='goalcheckin',
            index=models.Index(fields=['goal', '-scheduled_for'], name='api_goalche_goal_id_05dbd0_idx'),
        ),
        migrations.AddIndex(
            model_name='goalcheckin',
            index=models.Index(fields=['user', '-scheduled_for'], name='api_goalche_user_id_d70ac8_idx'),
        ),
        migrations.AddConstraint(
            model_name='goalcheckin',
            constraint=models.UniqueConstraint(fields=('goal', 'user', 'scheduled_for'), name='uniq_goal_user_checkin_date'),
        ),
        migrations.AddConstraint(
            model_name='goalcheckinbadge',
            constraint=models.UniqueConstraint(fields=('goal', 'scheduled_for', 'badge_type'), name='uniq_goal_checkin_badge_date_type'),
        ),
        migrations.AddConstraint(
            model_name='goalcheckinevidenceview',
            constraint=models.UniqueConstraint(fields=('checkin', 'user'), name='uniq_checkin_evidence_viewer'),
        ),
        migrations.AddConstraint(
            model_name='goalcheckinreaction',
            constraint=models.UniqueConstraint(fields=('checkin', 'user'), name='uniq_checkin_reaction_user'),
        ),
        migrations.AddIndex(
            model_name='subtaskreminderlog',
            index=models.Index(fields=['reminder_for_date'], name='api_subtask_reminde_b58ff0_idx'),
        ),
        migrations.AddConstraint(
            model_name='subtaskreminderlog',
            constraint=models.UniqueConstraint(fields=('task', 'user', 'reminder_for_date'), name='uniq_subtask_user_reminder_for_date'),
        ),
    ]
