# Generated by Django 6.0 on 2026-02-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accountdeletionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdeletionrequest',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
