# Generated by GitHub Copilot

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_accountdeletionrequest_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('otp_hash', models.CharField(max_length=256)),
                ('otp_expires_at', models.DateTimeField()),
                ('otp_used_at', models.DateTimeField(blank=True, null=True)),
                ('reset_token_hash', models.CharField(blank=True, default='', max_length=256)),
                ('reset_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('reset_token_used_at', models.DateTimeField(blank=True, null=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='password_reset_otps',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='passwordresetotp',
            index=models.Index(fields=['user', '-created_at'], name='accounts_pa_user_id_63e8e8_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresetotp',
            index=models.Index(fields=['otp_expires_at'], name='accounts_pa_otp_exp_00d47f_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresetotp',
            index=models.Index(fields=['reset_token_expires_at'], name='accounts_pa_reset_t_4c4d0c_idx'),
        ),
    ]
