# Generated by Django 6.0 on 2026-02-26 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_passwordresetotp'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordresetotp',
            new_name='accounts_pa_user_id_92b775_idx',
            old_name='accounts_pa_user_id_63e8e8_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresetotp',
            new_name='accounts_pa_otp_exp_a89065_idx',
            old_name='accounts_pa_otp_exp_00d47f_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresetotp',
            new_name='accounts_pa_reset_t_626391_idx',
            old_name='accounts_pa_reset_t_4c4d0c_idx',
        ),
    ]
