# Generated by Django 6.0 on 2026-06-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_accounts_pa_user_id_63e8e8_idx_accounts_pa_user_id_92b775_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_on_new_match',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_on_new_message',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_on_reminders',
            field=models.BooleanField(default=True),
        ),
    ]
