# Generated by Django 6.0.8 on 2026-09-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_last_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_on_milestones',
            field=models.BooleanField(default=True),
        ),
    ]
